######################################################################
# Automatically generated by qmake (3.1) Sun Dec 6 11:55:03 2020
######################################################################

TEMPLATE = app
TARGET = simpleViewer
INCLUDEPATH += .

QT  += widgets
QT  += opengl
QT  += xml
QT  += gui

LIBS += -lQGLViewer-qt5


HEADERS += simpleViewer.h
SOURCES += main.cpp simpleViewer.cpp
