/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ivizon_cubetest_NativeLib */

#ifndef _Included_com_ivizon_cubetest_NativeLib
#define _Included_com_ivizon_cubetest_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ivizon_cubetest_NativeLib
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ivizon_cubetest_NativeLib_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ivizon_cubetest_NativeLib
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ivizon_cubetest_NativeLib_step
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
