######################################################################
# Automatically generated by qmake (3.1) Tue Jul 17 13:30:16 2018
######################################################################

TEMPLATE = app
TARGET = test_qml
INCLUDEPATH += .

QT  += widgets quick

# Input
HEADERS += \
    src/test_qml.hpp
    
SOURCES += \
    src/test_qml.cpp \
    src/main.cpp 

RESOURCES += \
    src/main.qrc
