######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 19 16:08:51 2017
######################################################################

TEMPLATE = app
TARGET = Test
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
