######################################################################
# Automatically generated by qmake (3.0) ?? ????. 18 01:47:23 2013
######################################################################

TEMPLATE = app
TARGET = 1
INCLUDEPATH += .

QT += widgets

CONFIG += C++11

# Input
SOURCES += main.cpp \
    scene.cpp \
    figures/figure.cpp \
    tools.cpp \
    figures/rectfigure.cpp \
    figures/rhombfigure.cpp

HEADERS += \
    scene.h \
    figures/figure.h \
    tools.h \
    figures/rectfigure.h \
    figures/rhombfigure.h \
    figures/figure.h \
    figures/figuretype.h
