######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 22 21:46:19 2017
######################################################################

TEMPLATE    = app
TARGET      = Cube

DEPENDPATH  += . src
INCLUDEPATH += . src

greaterThan(QT_MAJOR_VERSION, 4) : QT += widgets

#CONFIG += opengl
QT      += opengl

# Input
HEADERS += src/cube.h
SOURCES += src/cube.cpp src/main.cpp
