sudo: required
language: cpp
compiler:
 - gcc
 - clang
env:
 - CONFIG=release	QT=4
 - CONFIG=debug		QT=4
 - CONFIG=release	QT=5
 - CONFIG=debug		QT=5
before_install: buildbots/travis-ci/01-before_install.sh
script: buildbots/travis-ci/02-script.sh
