#**********************************************************************************
#**                   Author: Bikbao Rinat Zinorovich                            **
#**********************************************************************************

#DEFINES += LOGO_GL

DEFINES += NO_STYLETOOLBAR
#DEFINES += NO_STATUSBAR
DEFINES += NO_TRAYICON
#DEFINES += NO_TOOLBAR
#DEFINES += NO_MENU
#DEFINES += NO_LOG

#DEFINES += SYSLOG_LOG

#DEFINES += ONLY_ENGLISH

#DEFINES += NO_TOOLBAR_BUTTON_EXIT
#DEFINES += NO_TOOLBAR_BUTTON_FONT
#DEFINES += NO_TOOLBAR_BUTTON_LANG
#DEFINES += NO_TOOLBAR_BUTTON_STYLE
#DEFINES += NO_TOOLBAR_BUTTON_ABOUT
#DEFINES += NO_TOOLBAR_BUTTON_HELP
#DEFINES += NO_TOOLBAR_SEPARATORS

DEFINES += PROGRAMM_IN_UTF8
#DEFINES += PROGRAMM_IN_KOI8R
#DEFINES += PROGRAMM_IN_CP1251
#DEFINES += PROGRAMM_IN_CP866

DEFINES += NEED_CODEC
#DEFINES += SAVE_INI

#DEFINES += USE_SCALE_POINT_DATETIME
#DEFINES += USE_SCALE_POINT_TIME

#DEFINES += USE_CUSTOM_STYLE

#DEFINES += TOOLBAR_ORIENTATION
#DEFINES += SHOW_SIZE

#DEFINES += SIMPLE_BROWSER
#DEFINES += IN_DEC

# DEFINES += SHOW_IP
# DEFINES += GET_SCREENSHOT

DEFINES += SINGLE_APP
DEFINES += USE_DOCK_WIDGETS

CONFIG(debug, debug|release) {
    DEFINES += SELF_TEST
    DEFINES += LOGGER_ON
}
