APP_MAJOR = 1
APP_MINOR = 0
APP_BUILD = 0
APP_PATCH = 0

DEFINES += APP_MAJOR=$${APP_MAJOR} 
DEFINES += APP_MINOR=$${APP_MINOR} 
DEFINES += APP_BUILD=$${APP_BUILD} 
DEFINES += APP_PATCH=$${APP_PATCH} 
