#**********************************************************************************
#**                   Author: Bikbao Rinat Zinorovich                            **
#**********************************************************************************

#DEFINES += LOGO_GL

DEFINES += DEF_NO_STYLETOOLBAR
#DEFINES += DEF_NO_STATUSBAR
DEFINES += DEF_NO_TRAYICON
#DEFINES += DEF_NO_TOOLBAR
#DEFINES += DEF_NO_MENU
#DEFINES += DEF_NO_LOG

#DEFINES += DEF_SYSLOG_LOG

#DEFINES += DEF_ONLY_ENGLISH

#DEFINES += DEF_NO_TOOLBAR_BUTTON_EXIT
#DEFINES += DEF_NO_TOOLBAR_BUTTON_FONT
#DEFINES += DEF_NO_TOOLBAR_BUTTON_LANG
#DEFINES += DEF_NO_TOOLBAR_BUTTON_STYLE
#DEFINES += DEF_NO_TOOLBAR_BUTTON_ABOUT
#DEFINES += DEF_NO_TOOLBAR_BUTTON_HELP
#DEFINES += DEF_NO_TOOLBAR_SEPARATORS

DEFINES += DEF_PROGRAMM_IN_UTF8
#DEFINES += DEF_PROGRAMM_IN_KOI8R
#DEFINES += DEF_PROGRAMM_IN_CP1251
#DEFINES += DEF_PROGRAMM_IN_CP866

DEFINES += DEF_NEED_CODEC
#DEFINES += DEF_SAVE_INI

DEFINES += DEF_SINGLE_APP
DEFINES += DEF_USE_DOCK_WIDGETS

CONFIG(debug, debug|release) {
    DEFINES += DEF_LOGGER_ON
}

DEFINES += HEX16
