######################################################################
# Automatically generated by qmake (3.0) ?? ??? 20 12:00:21 2018
######################################################################

TEMPLATE = app
TARGET = _Test
INCLUDEPATH += .

# Input
HEADERS += src/VideoTest.h
FORMS += src/ui/videotest.ui
SOURCES += src/videotest.cpp
