language: c
compiler:
  - gcc
os:
  - linux
  - osx
cache:
  directories:
  - $HOME/OpenBlasInstall
env:
  - TORCH_LUA_VERSION=LUAJIT21
  - TORCH_LUA_VERSION=LUA51
  - TORCH_LUA_VERSION=LUA52
addons:
  apt:
    packages:
    - cmake
    - gfortran
    - gcc-multilib
    - gfortran-multilib
    - liblapack-dev
    - build-essential
    - gcc 
    - g++ 
    - curl
    - cmake 
    - libreadline-dev 
    - git-core 
    - libqt4-core 
    - libqt4-gui
    - libqt4-dev 
    - libjpeg-dev 
    - libpng-dev 
    - ncurses-dev
    - imagemagick 
    - libzmq3-dev 
    - gfortran 
    - unzip 
    - gnuplot
    - gnuplot-x11 
    - libfftw3-dev 
    - sox 
    - libsox-dev
    - libsox-fmt-all
    - libgraphicsmagick1-dev
    - graphicsmagick
before_script: 
- export ROOT_TRAVIS_DIR=$(pwd)
- export INSTALL_PREFIX=~/torch/install
-  ls $HOME/OpenBlasInstall/lib || (cd /tmp/ && git clone https://github.com/xianyi/OpenBLAS.git -b master && cd OpenBLAS && (make NO_AFFINITY=1 -j$(getconf _NPROCESSORS_ONLN) 2>/dev/null >/dev/null) && make PREFIX=$HOME/OpenBlasInstall install)
- git clone https://github.com/torch/distro.git ~/torch --recursive
- cd ~/torch && ./install.sh -b
- source ~/torch/install/bin/torch-activate
- cd $ROOT_TRAVIS_DIR
- git clone https://github.com/Itseez/opencv
- cd opencv
- git checkout tags/3.1.0
- mkdir -p build && cd build
- cmake -DWITH_PYTHON=OFF .. && make
- cd $ROOT_TRAVIS_DIR
- git clone https://github.com/VisionLabs/torch-opencv
script: 
- cd torch-opencv
 OpenCV_DIR=${ROOT_DIR}/opencv/build luarocks make
