######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 18 17:25:56 2017
######################################################################

TEMPLATE = app
TARGET = Pong
DEPENDPATH += .
INCLUDEPATH += .

QT  += dbus

# Input
HEADERS += Pong.h ../serviceNameAndProperty.h
SOURCES += main.cpp Pong.cpp
