######################################################################
# Automatically generated by qmake (3.1) Fri Jan 7 14:28:27 2022
######################################################################

TEMPLATE = app
TARGET = Test_QOpenGLWidget
INCLUDEPATH += .

QT  += opengl

# Input
HEADERS += src/MyGLWidget.hpp
SOURCES += src/main.cpp src/MyGLWidget.cpp
