######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 18 13:49:56 2017
######################################################################

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE    = app
TARGET      = Test_QGraphicsView
DEPENDPATH  += . src
INCLUDEPATH += .

# Input
HEADERS += src/mainwindow.h
SOURCES += src/main.cpp src/mainwindow.cpp
