#**********************************************************************************
#**                   Author: Bikbao Rinat Zinorovich                            **
#**********************************************************************************

#DEFINES += LOGO_GL

DEFINES += NO_STYLETOOLBAR
#DEFINES += NO_STATUSBAR
#DEFINES += NO_TRAYICON
#DEFINES += NO_TOOLBAR
#DEFINES += NO_MENU
#DEFINES += NO_LOG

#DEFINES += SYSLOG_LOG

#DEFINES += ONLY_ENGLISH

#DEFINES += NO_TOOLBAR_BUTTON_EXIT
#DEFINES += NO_TOOLBAR_BUTTON_FONT
#DEFINES += NO_TOOLBAR_BUTTON_LANG
#DEFINES += NO_TOOLBAR_BUTTON_STYLE
#DEFINES += NO_TOOLBAR_BUTTON_ABOUT
#DEFINES += NO_TOOLBAR_BUTTON_HELP
#DEFINES += NO_TOOLBAR_SEPARATORS

DEFINES += PROGRAMM_IN_UTF8
#DEFINES += PROGRAMM_IN_KOI8R
#DEFINES += PROGRAMM_IN_CP1251
#DEFINES += PROGRAMM_IN_CP866

# DEFINES += USE_SCALE_POINT_DATETIME
# DEFINES += USE_SCALE_POINT_DATETIME_FULL    #для этого нужно включить USE_SCALE_POINT_DATETIME
DEFINES += USE_SCALE_POINT_TIME

DEFINES += NEED_CODEC
#DEFINES += SAVE_INI

#DEFINES += USE_CUSTOM_STYLE

DEFINES += SINGLE_APP
DEFINES += USE_DOCK_WIDGETS

DEFINES += ADD_CURVES

CONFIG(debug, debug|release) {
    DEFINES += LOGGER_ON
}
