#**********************************************************************************
#**                   Author: Bikbao Rinat Zinorovich                            **
#**********************************************************************************

#DEFINES += DEF_LOGO_GL
#DEFINES += DEF_FIXED_SIZE

#DEFINES += DEF_NO_STYLETOOLBAR
#DEFINES += DEF_NO_STATUSBAR
#DEFINES += DEF_NO_TRAYICON
#DEFINES += DEF_NO_TOOLBAR
#DEFINES += DEF_NO_MENU
#DEFINES += DEF_NO_LOG

#DEFINES += DEF_SYSLOG_LOG

#DEFINES += DEF_ONLY_ENGLISH

#DEFINES += DEF_NO_TOOLBAR_BUTTON_EXIT
#DEFINES += DEF_NO_TOOLBAR_BUTTON_FONT
#DEFINES += DEF_NO_TOOLBAR_BUTTON_LANG
#DEFINES += DEF_NO_TOOLBAR_BUTTON_STYLE
#DEFINES += DEF_NO_TOOLBAR_BUTTON_ABOUT
#DEFINES += DEF_NO_TOOLBAR_BUTTON_HELP
#DEFINES += DEF_NO_TOOLBAR_SEPARATORS

#DEFINES += DEMO
#DEFINES += "DEMO_YEAR=2020"
#DEFINES += "DEMO_MONTH=6"
#DEFINES += "DEMO_DAY=1"

#DEFINES += DEF_NO_LOG_INFO
#DEFINES += DEF_NO_LOG_DEBUG
#DEFINES += DEF_NO_LOG_ERROR
#DEFINES += DEF_NO_LOG_TRACE

#DEFINES += DEF_NO_LOG_QINFO
#DEFINES += DEF_NO_LOG_QDEBUG
#DEFINES += DEF_NO_LOG_QERROR
#DEFINES += DEF_NO_LOG_QTRACE

DEFINES += DEF_PROGRAMM_IN_UTF8
#DEFINES += DEF_PROGRAMM_IN_KOI8R
#DEFINES += DEF_PROGRAMM_IN_CP1251
#DEFINES += DEF_PROGRAMM_IN_CP866

#DEFINES += DEF_NEED_CODEC
DEFINES += DEF_SAVE_INI

#DEFINES += DEF_USE_SCALE_POINT_DATETIME
#DEFINES += DEF_USE_SCALE_POINT_TIME

#DEFINES += DEF_USE_CUSTOM_STYLE

#DEFINES += DEF_TOOLBAR_ORIENTATION
#DEFINES += DEF_SHOW_SIZE
#DEFINES += DEF_FAKE

#DEFINES += DEF_IN_DEC

DEFINES += DEF_SINGLE_APP
DEFINES += DEF_USE_DOCK_WIDGETS

#DEFINES += DEF_FILENAME_LOG

#DEFINES += DEF_TEST_DOCK

#DEFINES += DEF_ALWAYS_CONFIRM_EXIT

DEFINES += DEF_MESSAGE_AS_SPEECH

DEFINES += DEF_REMOTE_CONTROL

CONFIG(debug, debug|release) {
    DEFINES += DEF_LOGGER_ON
}
