######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 11 01:13:31 2016
######################################################################

TEMPLATE    = app
TARGET      = DLL
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += \
    $$(HOME)/BitTorrent_sync/WorkShare/incude/pet \
    src/petlib.h
    src/pet.h

SOURCES += \
    main.c src/petlib.c
