######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 27 16:07:02 2017
######################################################################

# http://blog.kislenko.net/show.php?id=1753&s=0

TEMPLATE    = app
TARGET      = _Template
DEPENDPATH  += .
INCLUDEPATH += .

SOURCES     += main.cpp
