######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 18 17:25:49 2017
######################################################################

TEMPLATE = app
TARGET = Ping
DEPENDPATH += .
INCLUDEPATH += .

QT  += dbus

# Input
HEADERS += Ping.h ../serviceNameAndProperty.h
SOURCES += main.cpp Ping.cpp
