######################################################################
# Automatically generated by qmake (3.0) ?? ????? 4 15:54:50 2015
######################################################################

TEMPLATE	= app
TARGET		= Test_QsLog

INCLUDEPATH 	+= . 3rdparty/QsLog

SOURCES += src/main.cpp

QMAKE_CFLAGS    += -std=c++11
QMAKE_CXXFLAGS  += -std=c++11
QMAKE_LFLAGS    += -std=c++11

include (3rdparty/QsLog/QsLog.pri)
