######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 31 23:36:30 2017
######################################################################

TEMPLATE = app
TARGET = ComboBoxDelegate
DEPENDPATH += . src
INCLUDEPATH += . src

QT  += widgets

# Input
HEADERS += src/ComboBoxDelegate.h
SOURCES += src/ComboBoxDelegate.cpp src/main.cpp
