######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 5 02:30:15 2017
######################################################################

TEMPLATE    = app
TARGET      = CallBackExampe_win
DEPENDPATH  += .
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += \
    mainwindow.h \
    square.h

SOURCES += \
    mainwindow.cpp \
    square.cpp \
    main.cpp

FORMS   += \
    mainwindow.ui
