#ifndef QTYANDEXAPI_GLOBAL_H
#define QTYANDEXAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTYANDEXAPI_LIBRARY)
#  define QTYANDEXAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTYANDEXAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTYANDEXAPI_GLOBAL_H
