######################################################################
# Automatically generated by qmake (3.1) Fri Nov 1 19:04:23 2019
######################################################################

TEMPLATE = app
TARGET = Test_RSA
INCLUDEPATH += .

DEPENDPATH  += \
    $$PWD/src \
    $$PWD/src/ui
INCLUDEPATH = $$DEPENDPATH

SOURCES += rsatest.cpp

CONFIG += crypto
LIBS += -lqca-qt5

VPATH = $$INCLUDEPATH
