#**********************************************************************************
#**                   Author: Bikbao Rinat Zinorovich                            **
#**********************************************************************************

QT  += sql qml
QT  += printsupport

DEPENDPATH  += \
           $$PWD \
           $$PWD/limereport \
           $$PWD/limereport/bands \
           $$PWD/limereport/items \
           $$PWD/limereport/databrowser \
           $$PWD/limereport/base \
           $$PWD/limereport/objectinspector \
           $$PWD/limereport/dialogdesigner \
           $$PWD/limereport/serializators \
           $$PWD/limereport/scripteditor \
           $$PWD/limereport/charts \
           $$PWD/limereport/editors \
           $$PWD/limereport/3rdparty \
           $$PWD/limereport/qtcreator \
           $$PWD/limereport/designer \
           $$PWD/limereport/designerintegrationv2 \
           $$PWD/limereport/objectsbrowser \
           $$PWD/limereport/scriptbrowser \
           $$PWD/limereport/translationeditor
INCLUDEPATH = $$DEPENDPATH

# Input
HEADERS += limereport/lraboutdialog.h \
           limereport/lraxisdata.h \
           limereport/lrbanddesignintf.h \
           limereport/lrbandsmanager.h \
           limereport/lrbasedesignintf.h \
           limereport/lrcallbackdatasourceintf.h \
           limereport/lrcollection.h \
           limereport/lrcolorindicator.h \
           limereport/lrdatadesignintf.h \
           limereport/lrdatasourceintf.h \
           limereport/lrdatasourcemanager.h \
           limereport/lrdatasourcemanagerintf.h \
           limereport/lrdesignelementsfactory.h \
           limereport/lrdesignerplugininterface.h \
           limereport/lrexporterintf.h \
           limereport/lrexportersfactory.h \
           limereport/lrfactoryinitializer.h \
           limereport/lrglobal.h \
           limereport/lrgraphicsviewzoom.h \
           limereport/lrgroupfunctions.h \
           limereport/lritemdesignintf.h \
           limereport/lritemscontainerdesignitf.h \
           limereport/lrpagedesignintf.h \
           limereport/lrpageinitintf.h \
           limereport/lrpageitemdesignintf.h \
           limereport/lrpreparedpages.h \
           limereport/lrpreparedpagesintf.h \
           limereport/lrpreviewreportwidget.h \
           limereport/lrpreviewreportwidget_p.h \
           limereport/lrpreviewreportwindow.h \
           limereport/lrreportdesignwidget.h \
           limereport/lrreportdesignwindow.h \
           limereport/lrreportdesignwindowintrerface.h \
           limereport/lrreportengine.h \
           limereport/lrreportengine_p.h \
           limereport/lrreportrender.h \
           limereport/lrreporttranslation.h \
           limereport/lrscriptenginemanager.h \
           limereport/lrscriptenginemanagerintf.h \
           limereport/lrsettingdialog.h \
           limereport/lrsimplecrypt.h \
           limereport/lrvariablesholder.h \
           limereport/bands/lrdataband.h \
           limereport/bands/lrgroupbands.h \
           limereport/bands/lrpagefooter.h \
           limereport/bands/lrpageheader.h \
           limereport/bands/lrreportfooter.h \
           limereport/bands/lrreportheader.h \
           limereport/bands/lrsubdetailband.h \
           limereport/bands/lrtearoffband.h \
           limereport/base/lrattribsabstractfactory.h \
           limereport/base/lrsimpleabstractfactory.h \
           limereport/base/lrsingleton.h \
           limereport/databrowser/lrconnectiondialog.h \
           limereport/databrowser/lrdatabrowser.h \
           limereport/databrowser/lrdatabrowsertree.h \
           limereport/databrowser/lrsqleditdialog.h \
           limereport/databrowser/lrvariabledialog.h \
           limereport/dialogdesigner/lrdialogdesigner.h \
           limereport/exporters/lrpdfexporter.h \
           limereport/items/lrabstractlayout.h \
           limereport/items/lralignpropitem.h \
           limereport/items/lrbarcodeitem.h \
           limereport/items/lrbordereditor.h \
           limereport/items/lrborderframeeditor.h \
           limereport/items/lrchartaxiseditor.h \
           limereport/items/lrchartitem.h \
           limereport/items/lrchartitemeditor.h \
           limereport/items/lreditableimageitemintf.h \
           limereport/items/lrhorizontallayout.h \
           limereport/items/lrimageitem.h \
           limereport/items/lrimageitemeditor.h \
           limereport/items/lrlayoutmarker.h \
           limereport/items/lrpageeditor.h \
           limereport/items/lrshapeitem.h \
           limereport/items/lrsimpletagparser.h \
           limereport/items/lrsubitemparentpropitem.h \
           limereport/items/lrsvgitem.h \
           limereport/items/lrtextitem.h \
           limereport/items/lrtextitemeditor.h \
           limereport/items/lrverticallayout.h \
           limereport/objectinspector/lrbasedesignobjectmodel.h \
           limereport/objectinspector/lrobjectinspectorwidget.h \
           limereport/objectinspector/lrobjectitemmodel.h \
           limereport/objectinspector/lrobjectpropitem.h \
           limereport/objectinspector/lrpropertydelegate.h \
           limereport/objectsbrowser/lrobjectbrowser.h \
           limereport/scriptbrowser/lrscriptbrowser.h \
           limereport/scripteditor/lrcodeeditor.h \
           limereport/scripteditor/lrcompletermodel.h \
           limereport/scripteditor/lrscripteditor.h \
           limereport/scripteditor/lrscripthighlighter.h \
           limereport/serializators/lrserializatorintf.h \
           limereport/serializators/lrstorageintf.h \
           limereport/serializators/lrxmlbasetypesserializators.h \
           limereport/serializators/lrxmlqrectserializator.h \
           limereport/serializators/lrxmlreader.h \
           limereport/serializators/lrxmlserializatorsfactory.h \
           limereport/serializators/lrxmlwriter.h \
           limereport/translationeditor/languageselectdialog.h \
           limereport/translationeditor/translationeditor.h \
           limereport/items/charts/lrgridlineschart.h \
           limereport/items/charts/lrhorizontalbarchart.h \
           limereport/items/charts/lrlineschart.h \
           limereport/items/charts/lrpiechart.h \
           limereport/items/charts/lrverticalbarchart.h \
           limereport/items/editors/lrfonteditorwidget.h \
           limereport/items/editors/lritemeditorwidget.h \
           limereport/items/editors/lritemsaligneditorwidget.h \
           limereport/items/editors/lritemsborderseditorwidget.h \
           limereport/items/editors/lrtextalignmenteditorwidget.h \
           limereport/objectinspector/editors/lrbuttonlineeditor.h \
           limereport/objectinspector/editors/lrcheckboxeditor.h \
           limereport/objectinspector/editors/lrcoloreditor.h \
           limereport/objectinspector/editors/lrcomboboxeditor.h \
           limereport/objectinspector/editors/lrfonteditor.h \
           limereport/objectinspector/editors/lrimageeditor.h \
           limereport/objectinspector/editors/lrsvgeditor.h \
           limereport/objectinspector/editors/lrtextitempropertyeditor.h \
           limereport/objectinspector/propertyItems/lraxispropitem.h \
           limereport/objectinspector/propertyItems/lrboolpropitem.h \
           limereport/objectinspector/propertyItems/lrcolorpropitem.h \
           limereport/objectinspector/propertyItems/lrcontentpropitem.h \
           limereport/objectinspector/propertyItems/lrdatasourcepropitem.h \
           limereport/objectinspector/propertyItems/lrenumpropitem.h \
           limereport/objectinspector/propertyItems/lrflagspropitem.h \
           limereport/objectinspector/propertyItems/lrfontpropitem.h \
           limereport/objectinspector/propertyItems/lrgroupfieldpropitem.h \
           limereport/objectinspector/propertyItems/lrimagepropitem.h \
           limereport/objectinspector/propertyItems/lrintpropitem.h \
           limereport/objectinspector/propertyItems/lrmarginpropitem.h \
           limereport/objectinspector/propertyItems/lrqrealpropitem.h \
           limereport/objectinspector/propertyItems/lrrectproptem.h \
           limereport/objectinspector/propertyItems/lrseriespropitem.h \
           limereport/objectinspector/propertyItems/lrstringpropitem.h \
           limereport/objectinspector/propertyItems/lrsvgpropitem.h \
           limereport/dialogdesigner/3rdparty/designer/pluginmanager_p.h \
           limereport/dialogdesigner/3rdparty/designer/qdesigner_integration_p.h \
           limereport/dialogdesigner/3rdparty/designer/shared_global_p.h \
           limereport/dialogdesigner/3rdparty/qtcreator/namespace_global.h \
           limereport/dialogdesigner/3rdparty/qtcreator/designerintegrationv2/formresizer.h \
           limereport/dialogdesigner/3rdparty/qtcreator/designerintegrationv2/sizehandlerect.h \
           limereport/dialogdesigner/3rdparty/qtcreator/designerintegrationv2/widgethost.h \
           limereport/dialogdesigner/3rdparty/qtcreator/designerintegrationv2/widgethostconstants.h
FORMS += limereport/lraboutdialog.ui \
         limereport/lrpreviewreportwidget.ui \
         limereport/lrpreviewreportwindow.ui \
         limereport/lrsettingdialog.ui \
         limereport/databrowser/lrconnectiondialog.ui \
         limereport/databrowser/lrdatabrowser.ui \
         limereport/databrowser/lrsqleditdialog.ui \
         limereport/databrowser/lrvariabledialog.ui \
         limereport/items/lrbordereditor.ui \
         limereport/items/lrborderframeeditor.ui \
         limereport/items/lrchartaxiseditor.ui \
         limereport/items/lrchartitemeditor.ui \
         limereport/items/lrimageitemeditor.ui \
         limereport/items/lrpageeditor.ui \
         limereport/items/lrtextitemeditor.ui \
         limereport/scriptbrowser/lrscriptbrowser.ui \
         limereport/scripteditor/lrscripteditor.ui \
         limereport/translationeditor/languageselectdialog.ui \
         limereport/translationeditor/translationeditor.ui \
         limereport/dialogdesigner/templates/Dialog.ui \
         limereport/objectinspector/editors/ltextitempropertyeditor.ui
SOURCES += limereport/lraboutdialog.cpp \
           limereport/lraxisdata.cpp \
           limereport/lrbanddesignintf.cpp \
           limereport/lrbandsmanager.cpp \
           limereport/lrbasedesignintf.cpp \
           limereport/lrcolorindicator.cpp \
           limereport/lrdatadesignintf.cpp \
           limereport/lrdatasourcemanager.cpp \
           limereport/lrfactoryinitializer.cpp \
           limereport/lrglobal.cpp \
           limereport/lrgraphicsviewzoom.cpp \
           limereport/lrgroupfunctions.cpp \
           limereport/lritemdesignintf.cpp \
           limereport/lritemscontainerdesignitf.cpp \
           limereport/lrpagedesignintf.cpp \
           limereport/lrpageitemdesignintf.cpp \
           limereport/lrpreparedpages.cpp \
           limereport/lrpreviewreportwidget.cpp \
           limereport/lrpreviewreportwindow.cpp \
           limereport/lrreportdesignwidget.cpp \
           limereport/lrreportdesignwindow.cpp \
           limereport/lrreportengine.cpp \
           limereport/lrreportrender.cpp \
           limereport/lrreporttranslation.cpp \
           limereport/lrscriptenginemanager.cpp \
           limereport/lrsettingdialog.cpp \
           limereport/lrsimplecrypt.cpp \
           limereport/lrvariablesholder.cpp \
           limereport/bands/lrdataband.cpp \
           limereport/bands/lrgroupbands.cpp \
           limereport/bands/lrpagefooter.cpp \
           limereport/bands/lrpageheader.cpp \
           limereport/bands/lrreportfooter.cpp \
           limereport/bands/lrreportheader.cpp \
           limereport/bands/lrsubdetailband.cpp \
           limereport/bands/lrtearoffband.cpp \
           limereport/databrowser/lrconnectiondialog.cpp \
           limereport/databrowser/lrdatabrowser.cpp \
           limereport/databrowser/lrdatabrowsertree.cpp \
           limereport/databrowser/lrsqleditdialog.cpp \
           limereport/databrowser/lrvariabledialog.cpp \
           limereport/dialogdesigner/lrdialogdesigner.cpp \
           limereport/exporters/lrpdfexporter.cpp \
           limereport/items/lrabstractlayout.cpp \
           limereport/items/lralignpropitem.cpp \
           limereport/items/lrbarcodeitem.cpp \
           limereport/items/lrbordereditor.cpp \
           limereport/items/lrborderframeeditor.cpp \
           limereport/items/lrchartaxiseditor.cpp \
           limereport/items/lrchartitem.cpp \
           limereport/items/lrchartitemeditor.cpp \
           limereport/items/lrhorizontallayout.cpp \
           limereport/items/lrimageitem.cpp \
           limereport/items/lrimageitemeditor.cpp \
           limereport/items/lrlayoutmarker.cpp \
           limereport/items/lrpageeditor.cpp \
           limereport/items/lrshapeitem.cpp \
           limereport/items/lrsimpletagparser.cpp \
           limereport/items/lrsubitemparentpropitem.cpp \
           limereport/items/lrsvgitem.cpp \
           limereport/items/lrtextitem.cpp \
           limereport/items/lrtextitemeditor.cpp \
           limereport/items/lrverticallayout.cpp \
           limereport/objectinspector/lrbasedesignobjectmodel.cpp \
           limereport/objectinspector/lrobjectinspectorwidget.cpp \
           limereport/objectinspector/lrobjectitemmodel.cpp \
           limereport/objectinspector/lrobjectpropitem.cpp \
           limereport/objectinspector/lrpropertydelegate.cpp \
           limereport/objectsbrowser/lrobjectbrowser.cpp \
           limereport/scriptbrowser/lrscriptbrowser.cpp \
           limereport/scripteditor/lrcodeeditor.cpp \
           limereport/scripteditor/lrcompletermodel.cpp \
           limereport/scripteditor/lrscripteditor.cpp \
           limereport/scripteditor/lrscripthighlighter.cpp \
           limereport/serializators/lrxmlbasetypesserializators.cpp \
           limereport/serializators/lrxmlqrectserializator.cpp \
           limereport/serializators/lrxmlreader.cpp \
           limereport/serializators/lrxmlwriter.cpp \
           limereport/translationeditor/languageselectdialog.cpp \
           limereport/translationeditor/translationeditor.cpp \
           limereport/items/charts/lrgridlineschart.cpp \
           limereport/items/charts/lrhorizontalbarchart.cpp \
           limereport/items/charts/lrlineschart.cpp \
           limereport/items/charts/lrpiechart.cpp \
           limereport/items/charts/lrverticalbarchart.cpp \
           limereport/items/editors/lrfonteditorwidget.cpp \
           limereport/items/editors/lritemeditorwidget.cpp \
           limereport/items/editors/lritemsaligneditorwidget.cpp \
           limereport/items/editors/lritemsborderseditorwidget.cpp \
           limereport/items/editors/lrtextalignmenteditorwidget.cpp \
           limereport/objectinspector/editors/lrbuttonlineeditor.cpp \
           limereport/objectinspector/editors/lrcheckboxeditor.cpp \
           limereport/objectinspector/editors/lrcoloreditor.cpp \
           limereport/objectinspector/editors/lrcomboboxeditor.cpp \
           limereport/objectinspector/editors/lrfonteditor.cpp \
           limereport/objectinspector/editors/lrimageeditor.cpp \
           limereport/objectinspector/editors/lrsvgeditor.cpp \
           limereport/objectinspector/editors/lrtextitempropertyeditor.cpp \
           limereport/objectinspector/propertyItems/lraxispropitem.cpp \
           limereport/objectinspector/propertyItems/lrboolpropitem.cpp \
           limereport/objectinspector/propertyItems/lrcolorpropitem.cpp \
           limereport/objectinspector/propertyItems/lrcontentpropitem.cpp \
           limereport/objectinspector/propertyItems/lrdatasourcepropitem.cpp \
           limereport/objectinspector/propertyItems/lrenumpropitem.cpp \
           limereport/objectinspector/propertyItems/lrflagspropitem.cpp \
           limereport/objectinspector/propertyItems/lrfontpropitem.cpp \
           limereport/objectinspector/propertyItems/lrgroupfieldpropitem.cpp \
           limereport/objectinspector/propertyItems/lrimagepropitem.cpp \
           limereport/objectinspector/propertyItems/lrintpropitem.cpp \
           limereport/objectinspector/propertyItems/lrmarginpropitem.cpp \
           limereport/objectinspector/propertyItems/lrqrealpropitem.cpp \
           limereport/objectinspector/propertyItems/lrrectproptem.cpp \
           limereport/objectinspector/propertyItems/lrseriespropitem.cpp \
           limereport/objectinspector/propertyItems/lrstringpropitem.cpp \
           limereport/objectinspector/propertyItems/lrsvgpropitem.cpp \
           limereport/dialogdesigner/3rdparty/qtcreator/designerintegrationv2/formresizer.cpp \
           limereport/dialogdesigner/3rdparty/qtcreator/designerintegrationv2/sizehandlerect.cpp \
           limereport/dialogdesigner/3rdparty/qtcreator/designerintegrationv2/widgethost.cpp
RESOURCES += limereport/report.qrc \
             limereport/databrowser/lrdatabrowser.qrc \
             limereport/dialogdesigner/dialogdesigner.qrc \
             limereport/items/items.qrc \
             limereport/objectinspector/lobjectinspector.qrc \
             limereport/scriptbrowser/lrscriptbrowser.qrc \
             limereport/translationeditor/translationeditor.qrc

VPATH = $$INCLUDEPATH
